### ISSUE TITLE
Creating zone always returns with error

### ISSUE THREAD

**Issue by andlinger** [InterNetX/java-domainrobot-sdk#15]
No matter if name servers are specified or not.

```
2020-08-18 13:23:15,776 SEVERE [a.t.w.b.s.BaseDomainrobotService] (executor-thread-207) Failed to contact AutoDNS api!: 20200818-app1-demo-32891 EF02052 : Nameserver wurde doppelt angegeben.
	at org.domainrobot.sdk.client.clients.AbstractClient.handleException(AbstractClient.java:173)
	at org.domainrobot.sdk.client.clients.ZoneClient.create(ZoneClient.java:50)
```

**Comment by Ephenodrom** [comment]
Hello @andlinger 

We will take a look into this. Do you have an code example to reproduce this problem ? The request body for 20200818-app1-demo-32891 was not logged on the demo system. Now I have no idea how the JSON body looked like in your request.

**Comment by andlinger** [comment]
Excuse me. That was my fault. 
But when creating a zone, which will be visible in the AutoDNS panel afterwards, a NullPointerException always happens when returning the zone object

```
2020-08-18 15:12:11,002 SEVERE [a.t.w.b.s.BaseDomainrobotService] (executor-thread-199) Failed to contact AutoDNS api!: java.lang.NullPointerException
	at org.domainrobot.sdk.client.clients.ZoneClient.create(ZoneClient.java:52)
```
