### ISSUE TITLE
ZoneClient#list doesn't work

### ISSUE THREAD

**Issue by andlinger** [InterNetX/java-domainrobot-sdk#23]
Calling the ZoneClient#list method always produces the following error message:

```
20201218-app3-137704 EF00004 : Ungueltiger Auftragstyp.
at org.domainrobot.sdk.client.clients.AbstractClient.handleException(AbstractClient.java:173)
at org.domainrobot.sdk.client.clients.ZoneClient.list(ZoneClient.java:165)
```

**Comment by Ephenodrom** [comment]
The problem was that the HTTP method was set to GET. For the zone list task we need the HTTP POST method.
