### ISSUE TITLE
Run error "com/fasterxml/jackson/annotation/JsonKey" and "setSources" not found

### ISSUE THREAD

**Issue by arstom** [InterNetX/java-domainrobot-sdk#27]
I'm not sure what I'm doing wrong but when I try to compile your example I get two issues.

**Cannot resolve method "setSources" in "DomainEnvelopeSearchRequest"**
`request.setSources(sources);`

**Exception at runtime**
`Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonKey
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.hasAsKey(JacksonAnnotationIntrospector.java:1080)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:495)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:421)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueAccessor(POJOPropertiesCollector.java:270)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueAccessor(BasicBeanDescription.java:258)
	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:391)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:220)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:169)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1473)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1421)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:520)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:798)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:308)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4487)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3742)
	at org.domainrobot.sdk.client.JsonUtils.serialize(JsonUtils.java:30)
	at org.domainrobot.sdk.client.clients.AbstractClient.buildRequestEntity(AbstractClient.java:148)
	at org.domainrobot.sdk.client.clients.AbstractClient.buildRequestEntity(AbstractClient.java:99)
	at org.domainrobot.sdk.client.clients.DomainStudioClient.search(DomainStudioClient.java:56)`

**Comment by arstom** [comment]
Thank you for making this merge. I will try it and give you some feedback.

**Comment by arstom** [comment]
Issue has been fixed.
